[package]
name = "teletext"
version = "0.1.3"
authors = ["Ross Nomann <rossnomann@protonmail.com>"]
edition = "2018"

[dependencies]
dotenv = "0.13.0"
env_logger = "0.6"
failure = "0.1.3"
log = "0.4"
teleborg = "0.1"
